<a href="https://colab.research.google.com/github/jonnie763/DATA-602-Intro-to-Data-Analysis-and-Machine-Learning/blob/main/Jonathan_Rius_Data_604_Project_5_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Helpful Sources: 

https://docs.google.com/document/d/10cz2uuhW93hppSaaGFyske1EpySJViKBoYGBVCIBgrQ/edit#heading=h.vvahj1spdx8g


https://colab.research.google.com/drive/13biHZxV28T3Fwh-sJryPn3fZwOr7ZKfv

https://colab.research.google.com/drive/15SLDgWAisEY37apGC91zffq577Zpnj0P

https://colab.research.google.com/drive/1lNQYWf3nabvsGF3evUy5gsKNJ8XaDuaf

https://colab.research.google.com/drive/193fTUNgJ0ECDzbocRCe6Tv4UsFwBM-mF

https://docs.google.com/presentation/d/1X0ggLVmA_3q5hlD5dh7HWpqXf_SMNQjnWk3XFjlJy3E/edit#slide=id.p

 **Project 5. Replicating CNN using RF and XGBoosting**

Assigned on Apr 26, 2022; Due on May 23, 2022

This is a fun project where you need to do a bit of research and deep dive into Computer Vision.
Please read about this dataset here. 

from sklearn import datasets
digits = datasets.load_digits()


You do not need to know much about deep learning or neural networks to understand how Convolutional Neural Networks (CNNs) work. Please feel free to check out this blog post about CNNs before you dive in. 

- You can think of convolutions as ways to manipulate your data and engineer the features in 2d and/or 3d space.

- Also check out other videos such as C4W1 Convolutional Neural Networks.

- You do not need to spend too much time understanding the neural network part. 

**Project Description and Objective**

- You will spend most of your time understanding the feature engineering perspective of a CNN.

- You will replicate how features (neurons) are generated using numpy (and/or pandas). 
 
- There is no limit on how you create new features, but you need to have at least 1 convoluted feature in your data.


Notes: Take the existing dataset and create an CNN within the dataset. Turn the dataset into a dataframe. Use the functions in the lecture to start. Start by turning the digits into a dataframe. Look at the lecture notes to determine where to start the project 5. Look at the last lecture notes (the code in there) to determine the result.

OK -  if you need general direction, I found this was a good way to start:

* load the data- this should be an easy one-liner
* convert into a dataframe -- check stack overflow for this
* run that data throughXGBoost and RandomForest, as-is
 - see class notes https://github.com/xinxueHEAI/ML602

* now go back and use the convolution algo from class to generate additional feature data
 - requires a little reshape()
- append output to dataset
- re-run through your models


# **PART ONE:** Describe how you generate new features using the data given: (50pts)


You need to have well defined python functions that input raw data and output features. 
(hint, think about the data structure before you implement this step.)

- You need to have detailed doc strings and comments on what each step of your functions are doing. 

- You will create a new feature called by CNN by generating them through pandas or numpy. You need to create an CNN through pandas with your dataset.


# 1) Load necessary libraries 

In [56]:
from sklearn import datasets # Libraries to create the CNN feature 

from sklearn.datasets import load_digits

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import average_precision_score

import pandas as pd

import seaborn as sns

import numpy as np

from matplotlib import pyplot as plt

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split, KFold

!pip install xgboost --upgrade

from xgboost.sklearn import XGBClassifier

digits = datasets.load_digits()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## 1a) Load data and convert into dataframe

In [57]:
digits

{'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 1797\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number o

In [58]:
digits=load_digits(as_frame=True)

X = digits.data
y = digits.target

In [59]:
X

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

In [60]:
X.shape

(1797, 64)

In [61]:
y

0       0
1       1
2       2
3       3
4       4
       ..
1792    9
1793    0
1794    8
1795    9
1796    8
Name: target, Length: 1797, dtype: int64

In [62]:
y.shape

(1797,)

## 1b) Run the data through random forest 

In [63]:
columns = X

In [64]:
# number of rows to draw
n_rows = X.shape[0] #first randomness in random forest
# number of columns to draw
n_col = int(np.sqrt(X.shape[1])) #second randomness in random forest
# number of copies <=>(learners / number of trees)
n_trees = 50

In [65]:
columns = X.columns

In [66]:
index = X.index

In [67]:
data_collection = []
for i in range(n_trees):
    row_draw = np.random.choice(index, size = n_rows,replace = True) #bootstrapping
    col_draw = np.random.choice(columns, size = n_col, replace = False) #draw columns
    data_collection.append((X.loc[row_draw,col_draw], y.iloc[row_draw], col_draw))

In [68]:
len(data_collection)

50

In [69]:
tree_collection = []

In [70]:
for i in data_collection:
    dt = DecisionTreeClassifier()
    dt.fit(X=i[0], y=i[1])
    tree_collection.append(dt)

In [71]:
prediction = []

In [72]:
for ind, i in enumerate(tree_collection):
    prediction.append(i.predict(X.loc[0:1,data_collection[ind][2]]))

In [73]:
# RF prediction for 1st row and 2nd row
np.mean(np.array(prediction).astype(int), axis = 0)

array([0.36, 1.36])

## 1b) Run the data through XGB

In [74]:
xgb = XGBClassifier(n_estimator = 20)

In [75]:
xgb.fit(X, y)

[22:16:35] WARNING: ../src/learner.cc:627: 
Parameters: { "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimator=20,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', predictor='auto', random_state=0, ...)

In [76]:
xgb.fit(X, y)

[22:16:47] WARNING: ../src/learner.cc:627: 
Parameters: { "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimator=20,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', predictor='auto', random_state=0, ...)

In [77]:
y_pred_xgb = xgb.predict(X)

## 1c) Use the convolution algo from class to generate additional features. Requires a little reshape().

In [115]:
x=load_digits()['images'][0].copy()

In [116]:
y= load_digits()['target'][0]

In [117]:
load_digits()['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [118]:
x

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [120]:
np.concatenate(x)

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [122]:
edge1=np.array([[1,0,1],[1,0,-1],[1,0,-1]])

In [123]:
edge1

array([[ 1,  0,  1],
       [ 1,  0, -1],
       [ 1,  0, -1]])

In [124]:
x[0:3,0:3]=edge1

In [126]:
edge2=np.ones(shape=(3,3))

In [138]:
def conv(x,edge,stride=1):
    k=edge.shape[0]
    n= x.shape [0]
    cache=[]
    for i in range (0,n-k,stride):
        for j in range (0,n-k,stride):
            val= (x[j:j+k,i:i+k]+edge).sum()
            cache.append(val)
        return cache

In [139]:
edge1=np.array([])

In [140]:
for edge in [edge1,edge2]:
    print(conv(x,edge))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[11.0, 25.0, 38.0, 53.0, 53.0]


## 1d) Append output to dataset

## 1e) Rerun the models through RGB and XGB

In [113]:
columns = X

In [80]:
# number of rows to draw
n_rows = X.shape[0] #first randomness in random forest
# number of columns to draw
n_col = int(np.sqrt(X.shape[1])) #second randomness in random forest
# number of copies <=>(learners / number of trees)
n_trees = 50

In [81]:
columns = X.columns

In [82]:
index = X.index

In [83]:
data_collection = []
for i in range(n_trees):
    row_draw = np.random.choice(index, size = n_rows,replace = True) #bootstrapping
    col_draw = np.random.choice(columns, size = n_col, replace = False) #draw columns
    data_collection.append((X.loc[row_draw,col_draw], y.iloc[row_draw], col_draw))

In [84]:
tree_collection = []

In [85]:
for i in data_collection:
    dt = DecisionTreeClassifier()
    dt.fit(X=i[0], y=i[1])
    tree_collection.append(dt)

In [86]:
prediction = []

In [87]:
for ind, i in enumerate(tree_collection):
    prediction.append(i.predict(X.loc[0:1,data_collection[ind][2]]))

In [88]:
# RF prediction for 1st row and 2nd row
np.mean(np.array(prediction).astype(int), axis = 0)

array([0.32, 1.78])

In [89]:
xgb = XGBClassifier(n_estimator=20)

In [90]:
xgb.fit(X, y)

[22:16:59] WARNING: ../src/learner.cc:627: 
Parameters: { "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimator=20,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', predictor='auto', random_state=0, ...)

In [91]:
y_predict_xgb = xgb.predict(X)


# **PART TWO: Fitting a RandomForest Classifier and a XGBClassifier. (30pts)**
You need to run a 3-fold cross validation on the hyperparameter sets

You need to included at least the following hyperparameters.

- Number of trees

- Min sample to split

- Maximum depth

- Please well utilize the `n_jobs` argument. 


# 2a) Fitting a RandomForest Classifier 

In [92]:
columns = X

In [93]:
# number of rows to draw
n_rows = X.shape[0] #first randomness in random forest
# number of columns to draw
n_col = int(np.sqrt(X.shape[1])) #second randomness in random forest
# number of copies <=>(learners / number of trees)
n_trees = 50

In [94]:
columns = X.columns

In [95]:
index = X.index

In [96]:
data_collection = []
for i in range(n_trees):
    row_draw = np.random.choice(index, size = n_rows,replace = True) #bootstrapping
    col_draw = np.random.choice(columns, size = n_col, replace = False) #draw columns
    data_collection.append((X.loc[row_draw,col_draw], y.iloc[row_draw], col_draw))

In [97]:
tree_collection = []

In [98]:
for i in data_collection:
    dt = DecisionTreeClassifier()
    dt.fit(X=i[0], y=i[1])
    tree_collection.append(dt)

In [99]:
prediction = []

In [100]:
for ind, i in enumerate(tree_collection):
    prediction.append(i.predict(X.loc[0:1,data_collection[ind][2]]))

In [101]:
# RF prediction for 1st row and 2nd row
np.mean(np.array(prediction).astype(int), axis = 0)

array([0.14, 1.5 ])

In [102]:
rf = RandomForestClassifier(n_estimators=10,)

In [104]:
rf.fit(X,y)

RandomForestClassifier(n_estimators=10)

In [105]:
rf.predict_proba(X.loc[0:1,:])[:,1]

array([0., 1.])

In [106]:
y_predict_rf = rf.predict(X)

# 2b) Fitting a XGBClassifier

In [109]:
xgb = XGBClassifier(n_estimator=20)

In [110]:
xgb.fit(X, y)

[22:17:50] WARNING: ../src/learner.cc:627: 
Parameters: { "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimator=20,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', predictor='auto', random_state=0, ...)

In [111]:
y_predict_xgb = xgb.predict(X)

# **PART THREE: Model Evaluation: (20pts)**
Compare the model performance of RF and Xgboosting. 

- You need to define your metric and elaborate on why you use the metric

- You need to print out some of the images that each model predicts the best, as well as those where each model fails.

- Discuss why you think the models fail and how they can improve.


# 3a) Compare the XGB and RF models through visualizations 

Notes: Hi professor I could not finish this part in time because of the group situation or lack there of. The best I could do is add notes to what my plans are for what how I would do model evaluation and how I would proceed with code. This is what I found comparing the models in a bullet list form. 



*   XGB Models are 
*   RF models are 

